apiVersion: v1
kind: ConfigMap
metadata:
  name: thinkcode-config
data:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://thinkcode:thinkcode123@host.docker.internal:5432/thinkcode?schema=public"
  REDIS_HOST: "redis.thinkcode.svc.cluster.local"
  REDIS_PORT: "6379"