apiVersion: v1
kind: Secret
metadata:
  name: thinkcode-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: "thinkcode123"
  JWT_SECRET: "dont be over smart"
  NEXT_PUBLIC_APP_URL: "http://localhost:30000"